export const Collections = {
	Users: "Users",
	Crews: "Crews",
	Workouts: "Workouts",
	Journeys: "Journeys",
	Missions: "Missions",
	Items: "Items",
	HealthyInfo: "HealthyInfo",
	Titles: "Titles",
	Achievements: "Achievements",
	Figures: "Figures",
	Files: "Files",
	UserDevices: "UserDevices",
	UserCheckIns: "UserCheckIns",
};
