export enum SystemErrors {
	
	// General
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	// Auth
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	// Crew
	CREW_NOT_FOUND = "CREW_NOT_FOUND",
	ALREADY_MEMBER = "ALREADY_MEMBER",
	ALREADY_IN_WHITELIST = "ALREADY_IN_WHITELIST",
	INVALID_DATE = "INVALID_DATE",
	FILE_NOT_PROVIDED = "FILE_NOT_PROVIDED",
	CANNOT_LEAVE_CREW_OWNER = "CANNOT_LEAVE_CREW_OWNER",
	// Workout
	INVALID_WORKOUT_DATE = "INVALID_WORKOUT_DATE",
	WORKOUT_DATE_IN_FUTURE = "WORKOUT_DATE_IN_FUTURE",
	WORKOUT_DATE_TOO_OLD = "WORKOUT_DATE_TOO_OLD",
	CREW_RULES_VIOLATION = "CREW_RULES_VIOLATION",
	WORKOUT_DATE_OLDER_THAN_CREW = "WORKOUT_DATE_OLDER_THAN_CREW",
	WORKOUT_NOT_FOUND = "WORKOUT_NOT_FOUND",
	// User
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_NOT_A_MEMBER = "USER_NOT_A_MEMBER",
	USER_NOT_IN_WHITELIST = "USER_NOT_IN_WHITELIST",
	ALREADY_FOLLOWING = "ALREADY_FOLLOWING",
	TITLE_NOT_FOUND = "TITLE_NOT_FOUND",
	USER_DOES_NOT_OWN_ITEM = "USER_DOES_NOT_OWN_ITEM",
	DEVICE_TOKEN_NOT_PROVIDED = "DEVICE_TOKEN_NOT_PROVIDED",
	
	// Journey
	JOURNEY_NOT_FOUND = "JOURNEY_NOT_FOUND",
	// Shop
	CART_IS_EMPTY = "CART_IS_EMPTY",
	SOME_ITEMS_ALREADY_OWNED = "SOME_ITEMS_ALREADY_OWNED",
	USER_NOT_MET_ITEMS_REQUIREMENTS = "USER_NOT_MET_ITEMS_REQUIREMENTS",
	USER_DO_NOT_HAVE_ENOUGH_COINS = "USER_DO_NOT_HAVE_ENOUGH_COINS",
	ITEM_NOT_FOUND = "ITEM_NOT_FOUND",
	// Missions
	MISSION_NOT_FOUND = "MISSION_NOT_FOUND",
	ALREADY_COMPLETED = "ALREADY_COMPLETED",
	MISSION_REQUIREMENTS_NOT_MET = "MISSION_REQUIREMENTS_NOT_MET",
	MISSION_ACHIEVEMENT_NOT_FOUND = "MISSION_ACHIEVEMENT_NOT_FOUND",
}

export type TSystemErrors = keyof typeof SystemErrors;
