name: Run Streak Job

on:
  schedule:
    - cron: '0 14 * * *' # every day at 14:00 UTC
  workflow_dispatch: # optional, allows manual run

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - name: Warm up service
        run: |
          curl -s https://your-api.onrender.com/ || true
      - name: Run streak job
        run: |
          sleep 60 # give Render time to boot the container
          curl -X POST https://your-api.onrender.com/internal/run-streak \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"
      - name: Call streak endpoint
        run: |
          for i in 1 2 3; do
            curl -X POST https://gym-mates.onrender.com/api/v1/jobs/check-users-streak \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" && break || sleep 30
          done
