name: Run Streak Job

on:
  schedule:
    - cron: '59 02 * * *' # Runs every day at 23:59 GMT-03
  workflow_dispatch: # optional, allows manual run

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - name: Call streak endpoint
        run: |
          curl -X POST https://gym-mates.onrender.com/api/v1/jobs/check-users-streak \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"
